// This file is auto-generated by scripts/generate-blog-manifest.mjs
// Do not edit manually.

export const blogModuleLoaders = {
  "ai-chatbots-for-business": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-chatbots-for-business/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-chatbots-for-business/zh.mdx"),
  },
  "ai-code-assistants-guide": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-code-assistants-guide/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-code-assistants-guide/zh.mdx"),
  },
  "ai-image-generators-compared": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-image-generators-compared/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-image-generators-compared/zh.mdx"),
  },
  "ai-productivity-tools-2025": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-productivity-tools-2025/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-productivity-tools-2025/zh.mdx"),
  },
  "ai-video-generation-tools": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-video-generation-tools/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-video-generation-tools/zh.mdx"),
  },
  "best-ai-tools-2025": {
    "en": () => import("../app/[locale]/(marketing)/blog/best-ai-tools-2025/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/best-ai-tools-2025/zh.mdx"),
  },
  "free-ai-tools-guide": {
    "en": () => import("../app/[locale]/(marketing)/blog/free-ai-tools-guide/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/free-ai-tools-guide/zh.mdx"),
  },
  "how-to-choose-ai-writing-tool": {
    "en": () => import("../app/[locale]/(marketing)/blog/how-to-choose-ai-writing-tool/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/how-to-choose-ai-writing-tool/zh.mdx"),
  },
} as const;
